apiVersion: v1
kind: Pod
metadata:
  name: corplan-pod
  labels:
    app: corplan
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:15-alpine
      env:
        - name: POSTGRES_DB
          value: corplan_rkap
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
          hostPort: 5436
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data

    - name: redis
      image: docker.io/library/redis:7-alpine
      ports:
        - containerPort: 6379
          hostPort: 6379
      volumeMounts:
        - mountPath: /data
          name: redis-data

    - name: calc-engine
      image: localhost/corplan-calc-engine:latest
      env:
        - name: PORT
          value: "8000"
      ports:
        - containerPort: 8000
          hostPort: 8001

    - name: api
      image: localhost/corplan-api:latest
      env:
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: corplan_rkap
        - name: CALC_ENGINE_URL
          value: http://localhost:8000
        - name: JWT_SECRET
          value: corplan_super_secret_key
      ports:
        - containerPort: 3000
          hostPort: 3017

    - name: web
      image: localhost/corplan-web:latest
      env:
        - name: API_URL
          value: http://localhost:3000
      ports:
        - containerPort: 80
          hostPort: 8080

  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: corplan-postgres-data
    - name: redis-data
      persistentVolumeClaim:
        claimName: corplan-redis-data
